### ISSUE TITLE
Successfully ingest all of 1000 Genomes Phase 3 VCF data

### ISSUE THREAD

**Issue by laserson** [cloudera/quince#15]
ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502/

**Comment by tomwhite** [comment]
I downloaded the VCFs into HDFS with the following

```bash
for chr in $(seq 1 22); do
  echo $chr
  hadoop fs -rm vcf-1000genomes/ALL.chr${chr}.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf
  curl ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502/ALL.chr${chr}.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz | gunzip -c | hadoop fs -put - vcf-1000genomes/ALL.chr${chr}.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf
done

hadoop fs -rm vcf-1000genomes/ALL.chrX.phase3_shapeit2_mvncall_integrated_v1b.20130502.genotypes.vcf
curl ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502/ALL.chrX.phase3_shapeit2_mvncall_integrated_v1b.20130502.genotypes.vcf.gz | gunzip -c | hadoop fs -put - vcf-1000genomes/ALL.chrX.phase3_shapeit2_mvncall_integrated_v1b.20130502.genotypes.vcf

hadoop fs -rm vcf-1000genomes/ALL.chrY.phase3_integrated_v1b.20130502.genotypes.vcf
curl ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502/ALL.chrY.phase3_integrated_v1b.20130502.genotypes.vcf.gz | gunzip -c | hadoop fs -put - vcf-1000genomes/ALL.chrY.phase3_integrated_v1b.20130502.genotypes.vcf
```

Next step is to run `LoadVariantsTool` on them.

**Comment by tomwhite** [comment]
I loaded chr1 and it took 4hrs, 14mins on a 6 node cluster. This was using the shuffle to do the sort.

When I tried to do the sort on the reduce side it ran out of memory after loading 24 million records into memory (for the first reducer that failed). (The YARN container had 64 GB of pmem, and 134.40 GB of vmem allocated to it.) Now, according to the successful run (shuffle sort) there are 16 billion records, so with 64 reducers, that's around 250 million records per reducer (on average; with skew it's not even since variants are not evenly distributed over the position buckets). That means the reducer loaded <10% of its variants into memory before it  ran out of memory. So, sorting in memory for 1000 genomes does not seem feasible.

Extrapolating to the whole dataset: it would take 4.23 hrs * (795.0 GB/61.3GB) = 55 hours (2 days, 7hrs) to run (using shuffle sort).

**Comment by tomwhite** [comment]
I realised that the above used too few reducers, so I reran with 250 reducers (since chr1 covers 250Mbps). The job completed in 3hrs 1 min. (So would take around 39hrs on the full dataset.)

I also tried re-running using sort on the reduce side (since each reduce would be doing less, since there were more of them), and giving each reducer 16GB of memory. The job still failed (time outs during sort, duplicate partition file names after retry), but with only a few reducers to go (at around the 2hrs mark) - so this may be feasible after all.

**Comment by tomwhite** [comment]
I've now added an option to restrict the samples that are loaded, and this makes it easier to load samples in batches. For example, you can load the 1K genomes dataset 100 samples at a time, and put each into a separate sample group. I've documented this approach here: https://github.com/cloudera/quince#loading-the-1000-genomes-vcf-data. Loading 100 samples (for the entire genome, not just chr1) takes 3hrs.

**Comment by laserson** [comment]
Running on a 10 node EC2 cluster, looks like the job takes ~2 hrs (with no shuffle)

**Comment by laserson** [comment]
(using c3.8xlarge I should say)

**Comment by tomwhite** [comment]
With the refactored code I managed to ingest 1K genomes in 5.5hrs on a 6 node cluster (with no shuffle).

```bash
hadoop jar target/quince-0.0.1-SNAPSHOT-job.jar \
  com.cloudera.science.quince.LoadVariantsTool \
  --sample-group 1000genomes \
  --flatten \
  vcf-1000genomes \
  datasets/variants_flat_locuspart
```

Closing this now.
