### ISSUE TITLE
Restructure LoadVariantsTool to simplify it

### ISSUE THREAD

**Issue by laserson** [cloudera/quince#30]
We want to support reading VCF, GA4GH, and ADAM, and writing GA4GH and ADAM.  We also want to support flattening of the schemas (though perhaps this is not necessary forever).  The DISTRIBUTE BY operation should be optional, if the input data is already globally sorted.  Here is a possible view of the flow:

![2015-10-15 12 40 19](https://cloud.githubusercontent.com/assets/118141/10529698/0a248f10-7355-11e5-8faa-8fdf8cd61813.jpg)

Perhaps the key idea is to get all the data, independent of the actual data model, to a `PCollection<key, SpecificRecord>` for the possible shuffle and the writing to Parquet.

**Comment by laserson** [comment]
I'm taking a crack at a sketch of this btw.  Should push it later tonight (by your morning)

**Comment by laserson** [comment]
One thing that I'm not sure I understand how to do in an idiomatic way is deal with the fact that there are 8 possible paths in the DAG:
* GA4GH or ADAM
* variants-only or genotype calls
* flatten or keep nested

This would be much easier with a dynamically typed language :)  I'm guessing that using `PCollection<Object>` and lots of casts is discouraged.

**Comment by tomwhite** [comment]
Great start. In terms of code organization I would keep all functionality out of the Tool classes; they should call into other classes that contain the actual code that does things (which can then be reused or called directly by clients). It would be good to remove the utility classes. `CrunchUtils` might be `VariantPartitioner` or similar.

The initial conversion can be encapsulated in functions like `VCFToADAMRecordsFn`. I'm not sure we need Parquet at this stage, so we'd have `{VCF,Avro}To{ADAM,GA4GH}RecordsFn`. Also, `AvroTo{ADAM,GA4GH}RecordsFn` would not be able to convert from ADAM Avro input data to a GA4GA model (say) - that would be an illegal conversion at the moment at least.

**Comment by tomwhite** [comment]
I think the eight possible paths are handled fairly well.

* __GA4GH or ADAM__
Currently only GA4GH is supported. Changing the code to pull out a key (contig, pos, sample_group, sample) and a SpecificRecord works well to support both.
* __Variants only or genotype calls__
This is handled in VCFToADAMRecordsFn (and VCFToGA4GHRecordsFn when implemented).
* __Flatten or keep nested__
We always flatten at the moment, but it will be useful to have the option to not flatten when Impala supports nested queries on Parquet data. Again, this is handled in VCFToADAMRecordsFn/VCFToGA4GHRecordsFn.

Other features we have now (and what to do with them)
* __Sort by sample ID (before position)__
We are not sure this is actually needed since sample groups provides a coarse partitioning that allows Hive/Impala to prune samples efficiently when querying. I.e. use sample groups judiciously to get efficient queries. Even in the case of gVCF we think that Parquet encoding will do a good job on expanded gVCF blocks (even if blocks don't align between gVCF files). In any case, we should try loading gVCF and only move to sort by sample ID if it is demonstrably better.
* __Restrict samples to include__
This is like `--samples` in bcftools and allows you to load a subset of the samples in a file. We should add this, but it's not urgent. It might be more useful to have a sample ID -> group mapping.
* __Sort reduce side__
This is an optimization that we probably don't need since in most cases VCFs are pre-sorted, so we can do a map-only job to load.

**Comment by laserson** [comment]
Ok, made a bunch of changes.  This compiles and the tests pass.  Some notes:
* The ADAM flattener is not yet implemented
* I had to add `spark-core` to the pom file just to get access to the `Logging` trait, which seems insane
* I haven't run this yet on a cluster or a data set, so perhaps there are now classpath issues?

**Comment by laserson** [comment]
The flow now looks more like

![2015-10-16 17 48 20](https://cloud.githubusercontent.com/assets/118141/10556032/56db4bb2-742e-11e5-931d-a8d6bc2c6bc6.jpg)

**Comment by laserson** [comment]
Also, you'll need to `generate-sources` again.

**Comment by tomwhite** [comment]
Fixed in https://github.com/cloudera/quince/pull/38
